#!/bin/sh

set -o nounset
set -o errexit
set -o pipefail


# ==== Constants and functions


BUILD_DEPS="curl tar"
RUNTIME_DEPS="php5-ctype php5-curl php5-dom php5-gd php5-iconv php5-json \
    php5-openssl php5-xml php5-xmlreader php5-zlib php5-zip"
DB_RUNTIME_DEPS="php5-mysql php5-pdo_mysql"


OWNCLOUD_ARCHIVE_URL="https://download.owncloud.org/community/owncloud-${OWNCLOUD_VERSION}.tar.bz2"
OWNCLOUD_DIST_PATH="/opt/web-app"


# ===== Main


apk add --no-cache ${BUILD_DEPS} ${RUNTIME_DEPS} ${DB_RUNTIME_DEPS}

mkdir -p "${OWNCLOUD_DIST_PATH}"
curl --silent --show-error "${OWNCLOUD_ARCHIVE_URL}" | \
    tar --extract --bzip2 --strip-components 1 --directory "${OWNCLOUD_DIST_PATH}" --verbose
chown --recursive www-data:www-data "${OWNCLOUD_DIST_PATH}"
find "${OWNCLOUD_DIST_PATH}" -type f -print0 | xargs -0 chmod 0640
find "${OWNCLOUD_DIST_PATH}" -type d -print0 | xargs -0 chmod 0750

mkdir -p "${OWNCLOUD_DATA_PATH}"
chown www-data:www-data "${OWNCLOUD_DATA_PATH}"

apk del --force ${BUILD_DEPS}
